database:
    type: sqlite3
    host: ""
    port: 0
    user: ""
    password: ""
    name: ""
    file: data/data.db
    sslmode: ""
    dsn: ""
env: dev
jwt:
    secret: your_secret_key
    expire: 604800
logger:
    loglevel: debug
    logfile:
        enable: true
        name: log/default.log
        maxsize: 128
        maxbackups: 300
        maxage: 30
        localtime: true
        compress: false
port: 3000
