info:
  contact: {}
paths:
  /api/user/{id}:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 获取用户
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: ""
      summary: 获取用户
      tags:
      - API.user
swagger: "2.0"
